name: "Test"

description: "Runs linters, type check and test."

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pnpm lint
        pnpm check
        cp playground/.env.example playground/.env
        pnpm -C=playground check
        pnpm test --coverage --coverage.reporter=text
