name: "Test"

description: "Runs linters, type check and test."

inputs:
  coverage:
    default: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pnpm lint
        pnpm check
        cp playground/.env.example playground/.env
        pnpm -C=playground check
        echo ${{ inputs.coverage }}
        pnpm test ${{ inputs.coverage == 'true' && '--coverage --coverage.reporter=text' || '' }}
