name: "Test"

description: "Runs linters, type check and test."

inputs:
  coverage:
    default: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pnpm lint
        pnpm check
        cp playground/.env.example playground/.env
        pnpm -C=playground check
        pnpm test ${{ inputs.coverage == 'true' && '--coverage' || '' }}

    - if: inputs.coverage == 'true'
      uses: actions/upload-artifact@v7
      with:
        name: coverage
        path: coverage/
