name: "Setup Deno and dependencies"
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v2
      with:
        cache: true
    - name: Install dependencies
      shell: bash
      run: deno install --frozen --allow-scripts=npm:@tailwindcss/oxide
