name: Tests

on:
  pull_request:

jobs:
  lint_and_type_check_and_test:
    name: Lint, type check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: ./.github/actions/setup-nodejs
      - name: Runs linters, type check and test
        uses: ./.github/actions/test-and-lint
